
import rose.mary.trace.support.console.SystemConsole;
import rose.mary.trace.support.install.InstallManager;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

	public String getGreeting() {
		return "Hello world.";
	}

	public static void main(String[] args) {

		try {
			if (args == null || args.length == 0 || args[0].equals("-c")) {

				String home = System.getProperty("console.home", System.getenv("user.dir"));
				String port = System.getProperty("console.port", "8090");
				SystemConsole console = new SystemConsole(home, port);
				console.start();

			} else if (args[0].equals("-i")) {
				InstallManager installManager = new InstallManager();
				installManager.install();
			} else if (args[0].equals("-in")) {
				InstallManager.checkOption = false;
				InstallManager installManager = new InstallManager();
				installManager.install();
			} else if (args[0].equals("-ir")) {
				InstallManager.checkOption = true;
				InstallManager.runOption = true;
				InstallManager installManager = new InstallManager();
				installManager.install();
			} else if (args[0].equals("-inr")) {
				InstallManager.checkOption = false;
				InstallManager.runOption = true;
				InstallManager installManager = new InstallManager();
				installManager.install();
			}
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
}
